name: MiDaS
channels:
  - pytorch
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates=2020.1.1
  - certifi=2019.11.28
  - cffi=1.13.2
  - cudatoolkit=10.0.130
  - cycler=0.10.0
  - freetype=2.9.1
  - hdf5=1.8.20
  - icu=58.2
  - intel-openmp=2019.4
  - jpeg=9b
  - kiwisolver=1.1.0
  - libopencv=3.4.2
  - libpng=1.6.37
  - libtiff=4.1.0
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - ninja=1.9.0
  - numpy=1.18.1
  - numpy-base=1.18.1
  - olefile=0.46
  - opencv=3.4.2
  - openssl=1.1.1d
  - pillow=6.2.0
  - pip=20.0.2
  - plac=1.1.0
  - py-opencv=3.4.2
  - pycparser=2.19
  - pyparsing=2.4.6
  - pyqt=5.9.2
  - python=3.7.6
  - python-dateutil=2.8.1
  - pytorch=1.2.0
  - qt=5.9.7
  - setuptools=45.1.0
  - sip=4.19.8
  - six=1.14.0
  - sqlite=3.31.1
  - tk=8.6.8
  - torchvision=0.4.0
  - tornado=6.0.3
  - wheel=0.34.2
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.3.7

